### ISSUE TITLE
Save to wav or audio file

### ISSUE THREAD

**Issue by rubywangruobin** [akseong/sonifyr#21]
Hi, I am very impressed by the work and trying to use the library on my project. Do you have a way to export the wplay audio into an audio file? The type of the wave is a num array. Thanks in advance!

**Comment by rubywangruobin** [comment]
Sorry for bothering, really not familiar with R. Got it done by using seewave

**Comment by akseong** [comment]
Hi Ruby, sorry I didn't see this earlier.  Yup, `seewave::savewav()` is actually what `wplay()` uses to save the audio file when you are knitting an .Rmd file.  I'd love to see/hear what you're doing with `datagoboop`!
